name: instagram
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.3.0
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  google_fonts: ^3.0.1
  curved_navigation_bar: ^1.0.3
  flutter_chat_ui: ^1.6.6
  image_picker: ^0.8.6
  file_picker: ^5.2.4
  open_filex: ^4.3.2
  path_provider: ^2.0.11
  mime: ^1.0.3
  cloud_firestore: ^4.2.0
  firebase_storage: ^11.0.8
  cached_network_image: ^3.2.3
  image_cropper: ^3.0.1
  fluttertoast: ^8.1.2
  internet_connection_checker: ^1.0.0+1
  assets_audio_player: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/